apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
  - dashboard.yaml
secretGenerator:
  - name: web-ingress-auth
    files:
      - auth
generatorOptions:
  disableNameSuffixHash: true