apiVersion: apps/v1
kind: Deployment
metadata:
  name: csirbd-demo
  labels:
    app: csirbd-demo
spec:
  replicas: 1
  template:
    metadata:
      name: csirbd-demo
      labels:
        app: csirbd-demo
    spec:
      containers:
        - name: web-server
          image: nginx
          volumeMounts:
            - name: mypvc
              mountPath: /var/lib/www/html
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: rbd-pvc
            readOnly: false
  selector:
    matchLabels:
      app: csirbd-demo
