apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-longhorn-claim
  namespace: registry-nfs
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: registry-nfs
  namespace: registry-nfs
spec:
  replicas: 1
  exports:
    - name: registry-share
      server:
        accessMode: ReadWrite
        squash: "none"
      persistentVolumeClaim:
        claimName: registry-longhorn-claim
