kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  hsts: "false"
  hsts-include-subdomains: "false"

  use-proxy-protocol: 'true'

  whitelist-source-range: "10.0.0.0/16,192.168.0.0/16"