apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - linkerd-support
  - nginx-ingress
  - hello-world
  - cert-manager
  - rook-nfs
  - longhorn
  - registry-nfs
  - registry
  - media-nfs
  - media-store
  - tekton
