---
- name: Configure sysctl
  sysctl:
    name: "{{ item.s }}"
    value: "{{ item.v }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { s: net.ipv4.ip_forward, v: 1 }

- name: Load loop
  modprobe:
    name: loop
    state: present
  changed_when: no # hack

- name: Install dependencies
  apt:
    name:
      - dmsetup
      - openssh-client
      - git
      - binutils
      - containerd
      - docker.io
      - e2fsprogs
      - mount
      - tar
      - jq
    install_recommends: no

- name: Check if swap file exists
  stat:
    path: "/swapfile"
  register: swap_file_check

- name: Disable SWAP since kubernetes can't work with swap enabled
  shell: |
    swapoff -a
  when: swap_file_check.stat.exists
