---
- name: Start containerd
  service:
    name: containerd
    state: started

- name: Start docker
  service:
    name: docker
    state: started

- name: Start iscsid
  service:
    name: iscsid
    state: started