apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-store
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: rook-cephfs-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-store-browser
  labels:
    app: media-store-browser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: media-store-browser
  template:
    metadata:
      labels:
        app: media-store-browser
    spec:
      containers:
        - name: media-store-browser
          image: pldubouilh/gossa
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: store
              mountPath: /shared/
          ports:
            - containerPort: 8001
      volumes:
        - name: store
          persistentVolumeClaim:
            claimName: media-store
            readOnly: false
