apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: example
  name: nfs-example-share
parameters:
  exportName: nfs-example-share
  nfsServerName: rook-nfs
  nfsServerNamespace: rook-nfs
provisioner: rook.io/nfs-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: "nfs-example-share"
---
