apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: alice
spec:
  resources:
    - name: source-repo
      type: git
    - name: alice-image
      type: image
  tasks:
    - name: build-alice-api
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/docker-source/api
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: alice-image
    - name: deploy-api
      taskRef:
        name: deploy-using-kustomize-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: alice-image
            from:
              - build-alice-api
      params:
        - name: path
          value: /workspace/source/api/platform/base/
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"