apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: velero-volume-controller
spec:
  resources:
    - name: source-repo
      type: git
    - name: velero-volume-controller-image
      type: image
  tasks:
    - name: build-velero-volume-controller
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: docker/Dockerfile
        - name: pathToContext
          value: /workspace/docker-source/vendor/velero-volume-controller/
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: velero-volume-controller-image
    - name: deploy-volume-controller
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: velero-volume-controller-image
            from:
              - build-velero-volume-controller
      params:
        - name: path
          value: /workspace/source/vendor/velero-volume-controller/examples/deployment/
        - name: file
          value: "velero-volume-controller.yaml"
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
        - name: namespace
          value: "velero"