apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.0
controlPlaneEndpoint: "{{ master_ip }}"
apiServer:
  certSANs:
    - "{{ nodeset_ip }}"
    - "{{ nodeset_master_hostname }}"
    - "{{ kubernetes_public_hostname }}"
