apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yml
  - issuer.yml
  - issuer-cloudflare-staging.yml
  - issuer-cloudflare.yml
  - issuer-buypass.yml

secretGenerator:
  - name: cloudflare-api-token-secret
    namespace: cert-manager
    files:
      - api-token

generatorOptions:
  disableNameSuffixHash: true