- hosts: dns
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - dns

- hosts: master-nodes, nodes
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - dependencies

- hosts: master-nodes
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - master
- hosts: nodes
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - node