- hosts: master-nodes
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - dependencies
    - master
#    - common
#    - ignite
#    - vm