apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-longhorn-claim
  namespace: media-nfs
spec:
  storageClassName: longhorn-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: media-nfs
  namespace: media-nfs
spec:
  replicas: 1
  exports:
    - name: media-share
      server:
        accessMode: ReadWrite
        squash: "none"
      persistentVolumeClaim:
        claimName: media-longhorn-claim
