namespace: metallb-system

resources:
  - namespace.yaml
  - metallb-0.9.2.yaml
configMapGenerator:
  - name: config
    files:
      - config

secretGenerator:
  - name: memberlist
    files:
      - secretkey

generatorOptions:
  disableNameSuffixHash: true
