apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pvc.yml
  - service.yml
  - ingress.yaml

secretGenerator:
  - name: transmission-settings
    files:
      - settings.json